.TH ORENDER 1
.SH NAME
orender \- render a rib file
.SH SYNOPSIS
\fBorender\fR [ -f <range> ] [ options ... ] [ -P:n | -t:n ] [ name.rib ...  ]
.br
\fBorender\fR -r <port>
.br
\fBorender\fR -k <port>
.br
\fBorender\fR [ options... ] [ name.rib ...  ] -s <srv1:port1,srv2:port2...>
.SH DESCRIPTION
.I  Orender
Renders a file with openRender.
.P
The main documentation is maintained in html form
and should be included with your distribution in the html or doc directories.
.P
Note: If the filename given is '-' or no filename is given, then
.I	orender
will read from standard input.  This is not valid for network renders, where the
file needs to be shipped to the server
.I orender
instances for them to read.
.SH OPTIONS
.TP
.B \-f <range>
Render only selected frames.  Range can be of the form N for a single frame, N1:N2
for N1 through to N2, or N1:N2:N3 for N1 to N3 skipping, but only every N2 frames.
.TP
.B \-q
Quiet mode.  Errors and warnings are not displayed.
.TP
.B \-d
Framebuffer display.  Overrides the display drivers and uses framebuffer.
.TP
.B \-t
Display statistics.  At the end of each frame, statistics are output.
.TP
.B \-p
Display progress.  Displays an updating progress line on the terminal.
.TP
.B \-P:n
Specify the number of subprocesses for a multiprocessor render.  May not be used with -r
or -s.
.TP
.B \-t:n
Specify the number of threads for a multithreaded render.  May not be used with -r or -s.
.TP
.B \-c <client port>
Specify a client (for subprocesses, used internally by orender).
.SH ENVIRONMENT
.TP
.B OPENRENDERHOME
The directory $(OPENRENDERHOME)/shaders is used to locate the display drivers, shaders, and
procedurals for a render.
.B OPENRENDERHOME
is contain the directories 'shaders' and 'displays', but may contain:
.RS
.TP
.B $(OPENRENDERHOME)/shaders
Location for shaders
.TP
.B $(OPENRENDERHOME)/displays
Location for display drivers
.TP
.B $(OPENRENDERHOME)/procedurals
Location for procedural generators
.TP
.B $(OPENRENDERHOME)/textures
Location for textures
.RE
.TP
.B SHADERS
Also searched for shaders
.TP
.B TEXTURES
Also searched for textures
.TP
.B PROCEDURALS
Also searched for procedurals
.TP
.B DISPLAYS
Also searched for display drivers
.TP
.B DISPLAY
Which X11 display to open for the framebuffer
.SH "SEE ALSO"
oshader(1), otexmake(1), oshow(1), rsloinfo(1)
.SH AUTHOR
See the sourceforge forums / tracker at http://openrender.sourceforge.net
