.TH OSHADER 1
.SH NAME
oshader \- compile an sl shader.
.SH SYNOPSIS
\fBoshader\fR [ options... ] [ name.sl ...  ]
.SH DESCRIPTION
.I  Oshader
Compiles renderman SL shaders to openRender sdr code for use with
.I orender.
.P
The main documentation is maintained in html form
and should be included with your distribution in the html or doc directories.
.SH OPTIONS
.TP
.B \-I<PATH>
Add <PATH> to the list of directories to search for the preprocessor (for includes).
.TP
.B \-D<SYMBOL>
Define <SYMBOL> for the preprocessor.  The name OPENRENDER is defined by default.
.TP
.B \-o <OUTNAME>
Output to <OUTNAME> regardless of shader names / input file name.
.TP
.B \-nw
Suppress warnings.
.TP
.B \-ne
Suppress errors.
.TP
.B \-ri
Display resolution info for names and functions.
.TP
.B \-v
Display version.
.TP
.B \--help
Display help.
.SH ENVIRONMENT
.TP
.B PATH
Searched for includes
.TP
.B SHADERS_INCLUDE
Additional include paths for the preprocessor
.TP
.B OPENRENDERHOME
Used to locate dsos.
.SH "SEE ALSO"
orender(1), otexmake(1), oshow(1), sdrinfo(1)
.SH BUGS
See the sourceforge forums / tracker at http://openrender.sourceforge.net
