#!/bin/bash

# Simple script to verify shader compiler extension behavior
# Usage: ./test_compiler_extension.sh /path/to/oshader

OSHADER=$1

if [ -z "$OSHADER" ]; then
    echo "Usage: $0 /path/to/oshader"
    exit 1
fi

TEST_SL="tests/shaders/test_materials.sl"
TEST_RSLO="test_materials.rslo"
TEST_SDR="test_materials.sdr"

# Cleanup
rm -f "$TEST_RSLO" "$TEST_SDR"

echo "Running Story 1 Test: Default compilation to .rslo"
$OSHADER "$TEST_SL"
if [ -f "$TEST_RSLO" ]; then
    echo "SUCCESS: .rslo file generated"
else
    echo "FAILURE: .rslo file NOT generated"
    exit 1
fi

if [ -f "$TEST_SDR" ]; then
    echo "FAILURE: .sdr file generated by default (should be .rslo)"
    exit 1
fi

rm -f "$TEST_RSLO"

echo "Running Story 1 Test: Legacy compilation to .sdr"
$OSHADER --legacy-sdr "$TEST_SL"
if [ -f "$TEST_SDR" ]; then
    echo "SUCCESS: .sdr file generated with --legacy-sdr"
else
    echo "FAILURE: .sdr file NOT generated with --legacy-sdr"
    exit 1
fi

if [ -f "$TEST_RSLO" ]; then
    echo "FAILURE: .rslo file generated with --legacy-sdr"
    exit 1
fi

# Cleanup
rm -f "$TEST_SDR"

echo "All Story 1 tests passed!"
exit 0
